// Ghidra headless post-script (Java GhidraScript -- Jython/PyGhidra Python
// scripting isn't available out of the box in this Ghidra build, so this
// is a straight port of find_psk_functions.py).
//
// Finds the functions that reference PSK-seal-related debug strings in the
// closed Goodix 53xc blob, decompiles them, and writes the pseudocode to a
// report file for offline analysis.

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Data;
import ghidra.program.model.listing.DataIterator;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.listing.Listing;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;
import ghidra.program.model.symbol.ReferenceManager;
import ghidra.util.task.ConsoleTaskMonitor;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class FindPskFunctions extends GhidraScript {

    private static final String[] TARGET_STRINGS = {
        "1.seal psk by sgx",
        "2.process encrypted psk",
        "3.write psk to mcu",
        "seal psk, ret 0x%x length before %d, length after:%d",
        "../common/sgx/PskUnify.c",
        "GfSealData",
        "GfSealData failed ",
        "GfUnsealData",
        "seal length:%d ",
    };

    private static final String OUTPUT_PATH =
        "/home/dhorn/goodix/goodix-533c-re/findings/ghidra-psk-decompile.md";

    @Override
    public void run() throws Exception {
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        StringBuilder out = new StringBuilder();
        out.append("# Ghidra decompilation: PSK-seal function trace\n");
        out.append("Auto-generated by ghidra_scripts/FindPskFunctions.java\n");

        Set<String> seenFunctions = new HashSet<>();
        List<Function> allDecompiled = new ArrayList<>();

        Listing listing = currentProgram.getListing();
        ReferenceManager refMgr = currentProgram.getReferenceManager();
        FunctionManager funcMgr = currentProgram.getFunctionManager();

        for (String target : TARGET_STRINGS) {
            out.append("\n## String: `").append(target).append("`\n");

            List<Address> addrs = findStringAddresses(listing, target);
            if (addrs.isEmpty()) {
                out.append("(not found as a defined-data string)\n");
                continue;
            }

            for (Address addr : addrs) {
                out.append("Found at address: ").append(addr).append("\n");

                Set<Function> functions = new HashSet<>();
                ReferenceIterator refs = refMgr.getReferencesTo(addr);
                while (refs.hasNext()) {
                    Reference ref = refs.next();
                    Function f = funcMgr.getFunctionContaining(ref.getFromAddress());
                    if (f != null) {
                        functions.add(f);
                    }
                }

                if (functions.isEmpty()) {
                    out.append("  (no function references this address)\n");
                    continue;
                }

                for (Function func : functions) {
                    String key = func.getEntryPoint().toString();
                    out.append("\n### Referencing function: ")
                       .append(func.getName()).append(" @ ")
                       .append(func.getEntryPoint()).append("\n");

                    if (seenFunctions.contains(key)) {
                        out.append("(already decompiled above, skipping duplicate)\n");
                        continue;
                    }
                    seenFunctions.add(key);
                    allDecompiled.add(func);

                    DecompileResults result = decomp.decompileFunction(func, 60, new ConsoleTaskMonitor());
                    if (result.decompileCompleted()) {
                        String code = result.getDecompiledFunction().getC();
                        out.append("```c\n").append(code).append("\n```\n");
                    } else {
                        out.append("(decompilation failed: ")
                           .append(result.getErrorMessage()).append(")\n");
                    }
                }
            }
        }

        out.append("\n## Caller context (one level up from each function above)\n");
        for (Function func : allDecompiled) {
            out.append("\n### Callers of ").append(func.getName())
               .append(" @ ").append(func.getEntryPoint()).append("\n");

            Set<Function> callerFuncs = new HashSet<>();
            ReferenceIterator refs = refMgr.getReferencesTo(func.getEntryPoint());
            while (refs.hasNext()) {
                Reference ref = refs.next();
                Function caller = funcMgr.getFunctionContaining(ref.getFromAddress());
                if (caller != null) {
                    callerFuncs.add(caller);
                }
            }

            if (callerFuncs.isEmpty()) {
                out.append("(no direct callers found -- may be called indirectly "
                    + "via function pointer/vtable)\n");
            }
            for (Function caller : callerFuncs) {
                out.append("- ").append(caller.getName()).append(" @ ")
                   .append(caller.getEntryPoint()).append("\n");
            }
        }

        try (FileWriter fw = new FileWriter(OUTPUT_PATH)) {
            fw.write(out.toString());
        }

        println("Wrote report to " + OUTPUT_PATH);
    }

    private List<Address> findStringAddresses(Listing listing, String needle) {
        List<Address> addrs = new ArrayList<>();
        DataIterator dataIter = listing.getDefinedData(true);
        while (dataIter.hasNext()) {
            Data data = dataIter.next();
            Object value;
            try {
                value = data.getValue();
            } catch (Exception e) {
                continue;
            }
            if (value instanceof String && value.equals(needle)) {
                addrs.add(data.getAddress());
            }
        }
        return addrs;
    }
}
