# Ghidra headless post-script (Jython-compatible syntax deliberately used --
# no f-strings, no type hints -- for compatibility with either Jython or
# PyGhidra's default scripting environment).
#
# Finds the functions that reference PSK-seal-related debug strings in the
# closed Goodix 53xc blob, decompiles them, and writes the pseudocode to a
# report file for offline analysis.
#
# Target strings, found via `strings` in Phase 1 (see findings/all-strings.txt):
#   "1.seal psk by sgx"
#   "2.process encrypted psk"
#   "3.write psk to mcu"
#   "seal psk, ret 0x%x length before %d, length after:%d"
#   "../common/sgx/PskUnify.c"
#   "GfSealData"
#   "GfSealData failed "
#   "GfUnsealData"

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor

TARGET_STRINGS = [
    "1.seal psk by sgx",
    "2.process encrypted psk",
    "3.write psk to mcu",
    "seal psk, ret 0x%x length before %d, length after:%d",
    "../common/sgx/PskUnify.c",
    "GfSealData",
    "GfSealData failed ",
    "GfUnsealData",
    "seal length:%d ",
    "seal psk, ret 0x%x length before %d, length after:%d",
]

OUTPUT_PATH = "/home/dhorn/goodix/goodix-533c-re/findings/ghidra-psk-decompile.md"


def find_string_addresses(program, needle):
    addrs = []
    listing = program.getListing()
    data_iter = listing.getDefinedData(True)
    for data in data_iter:
        try:
            value = data.getValue()
        except Exception:
            continue
        if isinstance(value, str) and value == needle:
            addrs.append(data.getAddress())
    return addrs


def get_referring_functions(program, addr):
    ref_mgr = program.getReferenceManager()
    refs = ref_mgr.getReferencesTo(addr)
    func_mgr = program.getFunctionManager()
    functions = set()
    for ref in refs:
        from_addr = ref.getFromAddress()
        func = func_mgr.getFunctionContaining(from_addr)
        if func is not None:
            functions.add(func)
    return functions


def main():
    program = currentProgram
    monitor = ConsoleTaskMonitor()

    decomp = DecompInterface()
    decomp.openProgram(program)

    out = []
    out.append("# Ghidra decompilation: PSK-seal function trace\n")
    out.append("Auto-generated by ghidra_scripts/find_psk_functions.py\n")

    seen_functions = set()

    for target in TARGET_STRINGS:
        out.append("\n## String: `{0}`\n".format(target))
        addrs = find_string_addresses(program, target)
        if not addrs:
            out.append("(not found as a defined-data string)\n")
            continue

        for addr in addrs:
            out.append("Found at address: {0}\n".format(addr))
            functions = get_referring_functions(program, addr)
            if not functions:
                out.append("  (no function references this address)\n")
                continue

            for func in functions:
                func_key = func.getEntryPoint().toString()
                out.append("\n### Referencing function: {0} @ {1}\n".format(
                    func.getName(), func.getEntryPoint()))

                if func_key in seen_functions:
                    out.append("(already decompiled above, skipping "
                                "duplicate)\n")
                    continue
                seen_functions.add(func_key)

                result = decomp.decompileFunction(func, 60, monitor)
                if result.decompileCompleted():
                    code = result.getDecompiledFunction().getC()
                    out.append("```c\n" + code + "\n```\n")
                else:
                    out.append("(decompilation failed: {0})\n".format(
                        result.getErrorMessage()))

    # Also list callers of every function we decompiled, one level up,
    # for control-flow context (who calls the seal/write sequence).
    out.append("\n## Caller context (one level up from each function "
                "above)\n")
    func_mgr = program.getFunctionManager()
    ref_mgr = program.getReferenceManager()
    for func_key in seen_functions:
        addr = program.getAddressFactory().getAddress(func_key)
        func = func_mgr.getFunctionAt(addr)
        if func is None:
            continue
        out.append("\n### Callers of {0} @ {1}\n".format(
            func.getName(), func.getEntryPoint()))
        refs = ref_mgr.getReferencesTo(func.getEntryPoint())
        caller_funcs = set()
        for ref in refs:
            caller = func_mgr.getFunctionContaining(ref.getFromAddress())
            if caller is not None:
                caller_funcs.add(caller)
        if not caller_funcs:
            out.append("(no direct callers found -- may be called "
                        "indirectly via function pointer/vtable)\n")
        for caller in caller_funcs:
            out.append("- {0} @ {1}\n".format(caller.getName(),
                                              caller.getEntryPoint()))

    with open(OUTPUT_PATH, "w") as f:
        f.write("".join(out))

    print("Wrote report to {0}".format(OUTPUT_PATH))


main()
